param(
    [ValidateSet("enable", "disable", "status")]
    [string]$Action = "enable"
)

$ErrorActionPreference = "Stop"

$root = $PSScriptRoot
$normalLauncher = Join-Path $root "start-hidden.vbs"
$bootLauncher = Join-Path $root "start-boot.vbs"
$startup = [Environment]::GetFolderPath("Startup")
$shortcutPath = Join-Path $startup "PLC Exporter.lnk"
$bootConfigPath = Join-Path $root "config.boot.cmd"
$taskName = "PLC Exporter - Boot"
$defaultKpiPath = "I:\Bor\11-Operative\02-ZooRoyal\07-Key Account Rewe Digital\Kapa Planung"

function Get-TaskFolder {
    $service = New-Object -ComObject "Schedule.Service"
    $service.Connect()
    return @{
        Service = $service
        Folder = $service.GetFolder("\")
    }
}

function Get-BootTask {
    try {
        $ctx = Get-TaskFolder
        return $ctx.Folder.GetTask($taskName)
    }
    catch {
        return $null
    }
}

function Remove-BootTask {
    try {
        $ctx = Get-TaskFolder
        $ctx.Folder.DeleteTask($taskName, 0)
        return $true
    }
    catch {
        return $false
    }
}

function New-StartupShortcut {
    $wscript = Join-Path $env:SystemRoot "System32\wscript.exe"
    if (-not (Test-Path -LiteralPath $wscript)) {
        throw "Chybi Windows Script Host: $wscript"
    }

    $shell = New-Object -ComObject WScript.Shell
    $shortcut = $shell.CreateShortcut($shortcutPath)
    $shortcut.TargetPath = $wscript
    $shortcut.Arguments = '"' + $normalLauncher + '"'
    $shortcut.WorkingDirectory = $root
    $shortcut.Description = "PLC Exporter - hidden startup fallback"
    $shortcut.WindowStyle = 7
    $shortcut.Save()
}

function Remove-StartupShortcut {
    Remove-Item -LiteralPath $shortcutPath -Force -ErrorAction SilentlyContinue
}

function Get-KpiPath {
    $configPath = Join-Path $root "config.cmd"
    if (Test-Path -LiteralPath $configPath) {
        foreach ($line in Get-Content -LiteralPath $configPath) {
            if ($line -match '^\s*set\s+"?KPI_EXCEL_PATH=(.*?)"?\s*$') {
                $value = $matches[1].Trim().Trim('"')
                if (-not [string]::IsNullOrWhiteSpace($value)) {
                    return $value
                }
            }
        }
    }
    return $defaultKpiPath
}

function Resolve-BootKpiPath {
    param([Parameter(Mandatory = $true)][string]$Path)

    if ($Path.StartsWith("\\")) {
        return @{
            Success = $true
            Path = $Path
            Message = "KPI cesta je UNC a je vhodna pro neinteraktivni start."
        }
    }

    if ($Path -notmatch '^([A-Za-z]):\\') {
        return @{
            Success = $true
            Path = $Path
            Message = "KPI cesta neni sitovy drive-letter path."
        }
    }

    $driveLetter = $matches[1].ToUpper()
    $deviceId = $driveLetter + ":"

    try {
        $disk = Get-CimInstance Win32_LogicalDisk -Filter ("DeviceID='" + $deviceId + "'") -ErrorAction Stop
    }
    catch {
        $disk = $null
    }

    if ($null -eq $disk) {
        if ($driveLetter -eq "C") {
            return @{ Success = $true; Path = $Path; Message = "KPI cesta je lokalni." }
        }
        return @{
            Success = $false
            Path = $Path
            Message = "Drive $deviceId neni dostupny, nelze pripravit spolehlivy boot start."
        }
    }

    if ([int]$disk.DriveType -ne 4) {
        return @{
            Success = $true
            Path = $Path
            Message = "KPI cesta je na lokalnim disku $deviceId."
        }
    }

    $provider = [string]$disk.ProviderName
    if ([string]::IsNullOrWhiteSpace($provider)) {
        return @{
            Success = $false
            Path = $Path
            Message = "Sitovy drive $deviceId nema zjistitelny UNC cil."
        }
    }

    $relative = $Path.Substring(3)
    $unc = $provider.TrimEnd("\") + "\" + $relative
    return @{
        Success = $true
        Path = $unc
        Message = "Sitovy drive $deviceId preveden pro boot na UNC: $unc"
    }
}

function Write-BootConfig {
    param(
        [Parameter(Mandatory = $true)][string]$NormalPath,
        [Parameter(Mandatory = $true)][string]$BootPath
    )

    if ($NormalPath -eq $BootPath) {
        Remove-Item -LiteralPath $bootConfigPath -Force -ErrorAction SilentlyContinue
        return
    }

    $content = @(
        "@rem AUTO-GENERATED by autostart.ps1 - boot-only overrides"
        ('set "KPI_EXCEL_PATH=' + $BootPath + '"')
        ""
    ) -join [Environment]::NewLine

    [IO.File]::WriteAllText($bootConfigPath, $content, [Text.UTF8Encoding]::new($false))
}

function Register-BootTask {
    param(
        [Parameter(Mandatory = $true)][PSCredential]$Credential
    )

    $wscript = Join-Path $env:SystemRoot "System32\wscript.exe"
    if (-not (Test-Path -LiteralPath $wscript)) {
        throw "Chybi Windows Script Host: $wscript"
    }

    $ctx = Get-TaskFolder
    $task = $ctx.Service.NewTask(0)

    $task.RegistrationInfo.Description = "PLC Exporter - hidden start at Windows boot"
    $task.Settings.Enabled = $true
    $task.Settings.StartWhenAvailable = $true
    $task.Settings.DisallowStartIfOnBatteries = $false
    $task.Settings.StopIfGoingOnBatteries = $false
    $task.Settings.MultipleInstances = 2
    $task.Settings.ExecutionTimeLimit = "PT10M"

    $TASK_TRIGGER_BOOT = 8
    $trigger = $task.Triggers.Create($TASK_TRIGGER_BOOT)
    $trigger.Enabled = $true

    $TASK_ACTION_EXEC = 0
    $action = $task.Actions.Create($TASK_ACTION_EXEC)
    $action.Path = $wscript
    $action.Arguments = '"' + $bootLauncher + '"'
    $action.WorkingDirectory = $root

    $userName = $Credential.UserName
    if ([string]::IsNullOrWhiteSpace($userName)) {
        throw "Windows uzivatel nebyl zadan."
    }

    $password = $Credential.GetNetworkCredential().Password
    if ([string]::IsNullOrWhiteSpace($password)) {
        throw "Prazdne heslo nelze pouzit pro start bez prihlaseni."
    }

    try {
        $TASK_CREATE_OR_UPDATE = 6
        $TASK_LOGON_PASSWORD = 1
        $ctx.Folder.RegisterTaskDefinition(
            $taskName,
            $task,
            $TASK_CREATE_OR_UPDATE,
            $userName,
            $password,
            $TASK_LOGON_PASSWORD,
            $null
        ) | Out-Null
    }
    finally {
        $password = $null
    }
}

function Enable-StartupFallback {
    Remove-BootTask | Out-Null
    Remove-Item -LiteralPath $bootConfigPath -Force -ErrorAction SilentlyContinue
    New-StartupShortcut

    Write-Host ""
    Write-Host "AUTOSTART MODE: STARTUP FALLBACK"
    Write-Host "Task Scheduler boot mode neni na tomto PC pouzitelny."
    Write-Host "PLC Exporter se spusti skryte po prihlaseni tohoto uzivatele."
    Write-Host "Shortcut: $shortcutPath"
}

function Enable-SmartAutostart {
    if (-not (Test-Path -LiteralPath $normalLauncher)) {
        throw "Chybi launcher: $normalLauncher"
    }
    if (-not (Test-Path -LiteralPath $bootLauncher)) {
        throw "Chybi boot launcher: $bootLauncher"
    }

    Write-Host "=========================================="
    Write-Host "PLC Exporter - chytry autostart"
    Write-Host "=========================================="
    Write-Host "1) Zkusim Task Scheduler: start uz pri bootu, bez prihlaseni."
    Write-Host "2) Pokud to Windows/politika nepovoli, nastavim Startup fallback."
    Write-Host ""

    $normalKpiPath = Get-KpiPath
    $resolved = Resolve-BootKpiPath -Path $normalKpiPath
    Write-Host $resolved.Message

    if (-not $resolved.Success) {
        Write-Host "BOOT TASK preskakuji, aby se nerozbila KPI Excel data."
        Enable-StartupFallback
        return
    }

    Write-BootConfig -NormalPath $normalKpiPath -BootPath $resolved.Path

    $identity = [Security.Principal.WindowsIdentity]::GetCurrent().Name
    Write-Host ""
    Write-Host "Pro start pred prihlasenim potrebuje Windows Task Scheduler ulozit"
    Write-Host "prihlasovaci udaje aktualniho uctu. Heslo se NEUKLADA do PLC-export souboru,"
    Write-Host "configu ani logu; predava se primo Windows Task Scheduleru."
    Write-Host "Uzivatel: $identity"
    Write-Host "Zruseni dialogu automaticky pouzije Startup fallback."
    Write-Host ""

    try {
        $credential = Get-Credential -UserName $identity -Message "PLC Exporter boot task - zadej Windows heslo"
        if ($null -eq $credential) {
            throw "Zadani prihlasovacich udaju bylo zruseno."
        }

        Register-BootTask -Credential $credential

        $task = Get-BootTask
        if ($null -eq $task) {
            throw "Task Scheduler po registraci ulohu nenalezl."
        }

        Remove-StartupShortcut

        Write-Host ""
        Write-Host "AUTOSTART MODE: BOOT TASK"
        Write-Host "OK - PLC Exporter je nastaven na start uz pri bootu Windows."
        Write-Host "Task: $taskName"
        Write-Host "Uzivatel: $($credential.UserName)"
        if (Test-Path -LiteralPath $bootConfigPath) {
            Write-Host "Boot KPI override: $bootConfigPath"
        }
    }
    catch {
        Write-Host ""
        Write-Host ("Boot task nebyl aktivovan: " + $_.Exception.Message)
        Write-Host "Pouzivam bezpecny fallback bez admin prav."
        Enable-StartupFallback
    }
}

function Show-Status {
    $task = Get-BootTask
    $shortcutExists = Test-Path -LiteralPath $shortcutPath

    Write-Host "=========================================="
    Write-Host "PLC Exporter - autostart status"
    Write-Host "=========================================="

    if ($null -ne $task) {
        Write-Host "MODE: BOOT TASK"
        Write-Host "Task: $taskName"
        Write-Host ("State: " + $task.State)
        Write-Host ("LastTaskResult: " + $task.LastTaskResult)
        if (Test-Path -LiteralPath $bootConfigPath) {
            Write-Host "Boot KPI override: present"
        } else {
            Write-Host "Boot KPI override: not needed"
        }
        if ($shortcutExists) {
            Write-Host "WARNING: Startup fallback shortcut take existuje; disable/enable ho uklidi."
        }
        return 0
    }

    if ($shortcutExists) {
        Write-Host "MODE: STARTUP FALLBACK"
        Write-Host "Spusteni: po prihlaseni uzivatele"
        Write-Host "Shortcut: $shortcutPath"
        return 0
    }

    Write-Host "MODE: DISABLED"
    return 1
}

switch ($Action) {
    "enable" {
        Enable-SmartAutostart
    }

    "disable" {
        $taskRemoved = Remove-BootTask
        Remove-StartupShortcut
        Remove-Item -LiteralPath $bootConfigPath -Force -ErrorAction SilentlyContinue

        Write-Host "AUTOSTART DISABLED"
        if ($taskRemoved) {
            Write-Host "Boot task odstranen nebo nebyl pritomen."
        } else {
            Write-Host "Boot task nebyl nalezen nebo ho Windows nedovolil odstranit."
        }
        Write-Host "Startup shortcut odstranen."
    }

    "status" {
        exit (Show-Status)
    }
}
